// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	model "blog-api/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// PostStorage is an autogenerated mock type for the PostStorage type
type PostStorage struct {
	mock.Mock
}

// Create provides a mock function with given fields: newPost
func (_m *PostStorage) Create(newPost model.NewPost) model.Post {
	ret := _m.Called(newPost)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Post
	if rf, ok := ret.Get(0).(func(model.NewPost) model.Post); ok {
		r0 = rf(newPost)
	} else {
		r0 = ret.Get(0).(model.Post)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *PostStorage) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *PostStorage) GetAll() []model.Post {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Post
	if rf, ok := ret.Get(0).(func() []model.Post); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Post)
		}
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *PostStorage) GetByID(id int) (model.Post, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (model.Post, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) model.Post); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Post)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, updatedPost
func (_m *PostStorage) Update(id int, updatedPost model.NewPost) (model.Post, error) {
	ret := _m.Called(id, updatedPost)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(int, model.NewPost) (model.Post, error)); ok {
		return rf(id, updatedPost)
	}
	if rf, ok := ret.Get(0).(func(int, model.NewPost) model.Post); ok {
		r0 = rf(id, updatedPost)
	} else {
		r0 = ret.Get(0).(model.Post)
	}

	if rf, ok := ret.Get(1).(func(int, model.NewPost) error); ok {
		r1 = rf(id, updatedPost)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPostStorage creates a new instance of PostStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostStorage {
	mock := &PostStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
